version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.0-node

    working_directory: ~/eg

    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: lein clj-test-pass
      - run: lein cljs-test-pass
      # test coverage only for: lein clj-test-pass
      - run: CLOVERAGE_VERSION=1.1.1 lein cloverage --codecov
      - codecov/upload:
          file: {{ target/coverage/codecov.json }}