#!/bin/sh

# source: https://jmglov.net/blog/2022-08-09-dogfooding-blambda-2.html

set -e

export BABASHKA_DISABLE_SIGNAL_HANDLERS="true"

export XDG_CACHE_HOME=/opt
export XDG_CONFIG_HOME=/opt
export XDG_DATA_HOME=/opt
export HOME=/var/task
export GITLIBS=/opt
export CLOJURE_TOOLS_DIR=/opt
export CLJ_CACHE=/opt
export CLJ_CONFIG=/opt

export BABASHKA_CLASSPATH="/opt/.m2:var/task/src:/var/task/.m2:/var/task:/var/task/src/clj:/var/task/src/cljc:src/cljc:src/clj:/var/task/resources"

bb -Duser.home=/var/task "$@"
