name: CI

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo in current branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref || github.ref_name }}
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install Leiningen
      run: |
        curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
        mv lein /usr/local/bin/
        chmod a+x /usr/local/bin/lein
    - name: Install Babashka
      run: bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
    - name: Run Babashka unit and integration tests
      run: bb run test-bb
    - name: Create POM file for bb e2e tests
      run: lein pom
    - name: Run Babashka e2e tests
      working-directory: ${{ github.workspace }}/test/e2e/bb
      run: bb test.clj
    - name: Install dependencies
      run: lein deps
    - name: Run Clojure unit tests
      run: lein clj-test-pass-unit
    - name: Run ClojureScript unit tests
      run: lein cljs-test-pass-unit
    - name: Run Clojure integration tests
      run: lein clj-test-pass-integration
    - name: Run ClojureScript integration tests
      run: lein cljs-test-pass-integration
    - name: Install ripgrep
      run: |
        curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
        sudo dpkg -i ripgrep_13.0.0_amd64.deb
    - name: Run failing tests
      run: |
        (! lein clj-test-fail) | tee /dev/tty | rg --quiet --multiline '25 assertions.*\n.*25 failures'
        lein cljs-test-fail | tee /dev/tty | rg --quiet --multiline '25 assertions.*\n.*25 failures'
    - name: Install Lumo
      run: npm install -g --unsafe-perm lumo-cljs
    - name: Test JavaScript JS using Lumo
      run: lein tach lumo
    - name: Create code coverage report
      run: CLOVERAGE_VERSION=1.1.1 lein coverage
    - name: Upload code coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: target/coverage/codecov.json
